const CountryData = [
  {
    name: "afghanistan",
    names: ['afghanistan'],
    capital: "kabul",
    capitals: ["kabul"],
    abbr: "af",
    borders: [
      "china",
      "iran",
      "pakistan",
      "tajikistan",
      "turkmenistan",
      "uzbekistan",
    ],
  },
  {
    name: "albania",
    names: ['albania'],
    capital: "tirana",
    capitals: ["tirana"],
    abbr: "al",
    borders: ["greece", "kosovo", "montenegro", "north macedonia"],
  },
  {
    name: "algeria",
    names: ["algeria"],
    capital: "algiers",
    capitals: ["algiers"],
    abbr: "dz",
    borders: ["libya", "mali", "mauritania", "morocco", "niger", "tunisia"],
  },
  {
    name: "andorra",
    names: ["andorra"],
    capital: "andorra la vella",
    capitals: ["andorra la vella", "la vella"],
    abbr: "ad",
    borders: ["france", "spain"],
  },
  {
    name: "angola",
    names: ["angola"],
    capital: "luanda",
    capitals: ["luanda"],
    abbr: "ao",
    borders: ["democratic republic of the congo", "namibia", "zambia"],
  },
  {
    name: "antigua and barbuda",
    names: ["antigua and barbuda", "antigua", "barbuda"],
    capital: "saint johns",
    capitals: ["saint johns", "st johns", "st. johns"],
    abbr: "ag",
    borders: [],
  },
  {
    name: "argentina",
    names: ["argentina"],
    capital: "buenos aires",
    capitals: ["buenos aires", "buenosaires"],
    abbr: "ar",
    borders: ["bolivia", "brazil", "chile", "paraguay", "uruguay"],
  },
  {
    name: "armenia",
    names: ["armenia"],
    capital: "yerevan",
    capitals: ["yerevan"],
    abbr: "am",
    borders: ["azerbaijan", "georgia", "iran", "turkey"],
  },
  {
    name: "australia",
    names: ["australia"],
    capital: "",
    capitals: ["canberra"],
    abbr: "au",
    borders: [],
  },
  {
    name: "austria",
    names: ["austria"],
    capital: "",
    capitals: ["vienna"],
    abbr: "at",
    borders: [
      "czechia",
      "germany",
      "hungary",
      "italy",
      "liechtenstein",
      "slovakia",
      "slovenia",
      "switzerland",
    ],
  },
  {
    name: "azerbaijan",
    names: ["azerbaijan"],
    capital: "baku",
    capitals: ["baku"],
    abbr: "az",
    borders: ["armenia", "georgia", "iran", "russia", "turkey"],
  },
  {
    name: "the bahamas",
    names: ["bahamas", "the bahamas"],
    capital: "nassau",
    capitals: ["nassau"],
    abbr: "bs",
    borders: [],
  },
  {
    name: "bahrain",
    names: ["bahrain"],
    capital: "manama",
    capitals: ["manama"],
    abbr: "bh",
    borders: [],
  },
  {
    name: "bangladesh",
    names: ["bangladesh"],
    capital: "dhaka",
    capitals: ["dhaka"],
    abbr: "bd",
    borders: ['india', 'myanmar'],
  },
  {
    name: "barbados",
    names: ["barbados"],
    capital: "bridgetown",
    capitals: ["bridgetown", "bridge town"],
    abbr: "bb",
    borders: [],
  },
  {
    name: "belarus",
    names: ["belarus"],
    capital: "minsk",
    capitals: ["minsk"],
    abbr: "by",
    borders: ['latvia', 'lithuania', 'poland', 'russia', 'ukraine'],
  },
  {
    name: "belgium",
    names: ["belgium"],
    capital: "brussels",
    capitals: ["brussels"],
    abbr: "be",
    borders: ['france', 'germany', 'luxembourg', 'the netherlands'],
  },
  {
    name: "belize",
    names: ["belize"],
    capital: "belmopan",
    capitals: ["belmopan"],
    abbr: "bz",
    borders: ['guatemala', 'mexico'],
  },
  {
    name: "benin",
    names: ["benin"],
    capital: "porto-novo",
    capitals: ["porto-novo", "porto novo"],
    abbr: "bj",
    borders: ['burkina faso', 'niger', 'nigeria', 'togo'],
  },
  {
    name: "bhutan",
    names: ["bhutan"],
    capital: "thimphu",
    capitals: ["thimphu"],
    abbr: "bt",
    borders: ['china', 'india'],
  },
  {
    name: "bolivia",
    names: ["bolivia"],
    capital: "la paz / sucre",
    capitals: ["la paz", "sucre", "lapaz", "la paz / sucre", "la paz and sucre"],
    abbr: "bo",
    borders: ['argentina', 'brazil', 'chile', 'paraguay', 'peru'],
  },
];

export default CountryData;
