import CountriesInformationDisplay from "./components/CountriesInformationDisplay";

const countryNames = {
afghanistan: ['afghanistan'],
albania: ['albania'],
algeria: ["algeria"],
andorra: ["andorra"],
angola: ["angola"],
antiguaBarbuda: ["antigua and barbuda", "antigua", "barbuda"],
argentina: ["argentina"],
armenia: ["armenia"],
australia: ["australia"],
austria: ["austria"],
azerbaijan: ["azerbaijan"],
bahamas: ["the bahamas", "bahamas"],
bahrain: ["bahrain"],
bangladesh: ["bangladesh"],
barbados: ["barbados"],
belarus: ["belarus"],
belgium: ["belgium"],
belize: ["belize"],
benin: ["benin"],
bhutan: ["bhutan"],
bolivia: ["bolivia"],
bosniaHerzegovina: [],
botswana: [],
brazil: ["brazil"],
brunei: [],
bulgaria: [],
burkinaFaso: ["burkina faso", "burkinafaso"],
burundi: [],
capeVerde: [],
cambodia: [],
cameroon: [],
canada: [],
centralAfricanRepublic: [],
chad: [],
chile: ["chile"],
china: ["china"],
colombia: [],
comoros: [],
costaRica: [],
croatia: [],
cuba: [],
cyprus: [],
czechia: ["czechia", "czech republic", "czechrepublic", "the czech republic"],
coteDIvoire: [],
democraticCongo: ["democratic republic of the congo", "democratic congo", "drc", "congo"],
denmark: [],
djibouti: [],
dominica: [],
dominicanRepublic: [],
ecuador: [],
egypt: [],
elSalvador: [],
equatorialGuinea: [],
eritrea: [],
estonia: [],
eswatini: [],
ethiopia: [],
fiji: [],
finland: [],
france: ["france"],
gabon: [],
gambia: [],
georgia: ["georgia"],
germany: ["germany"],
ghana: [],
greece: ["greece"],
grenada: [],
guatemala: ["guatemala"],
guinea: [],
guineaBissau: [],
guyana: [],
haiti: [],
honduras: [],
hungary: ["hungary"],
iceland: [],
india: ["india"],
indonesia: [],
iran: ["iran"],
iraq: [],
ireland: [],
israel: [],
italy: ["italy"],
japan: [],
jordan: [],
kazakhstan: [],
kenya: [],
kiribati: [],
kosovo: ["kosovo"],
kuwait: [],
kyrgyzstan: [],
laos: [],
latvia: ["latvia"],
lebanon: [],
lesotho: [],
liberia: [],
libya: ["libya"],
liechtenstein: ["liechtenstein"],
lithuaina: ["lithuania"],
luxembourg: ["luxembourg"],
madagascar: [],
malawi: [],
malaysia: [],
maldives: [],
mali: ["mali"],
malta: [],
marshallIslands: [],
mauritania: ['mauritania'],
mauritius: [],
mexico: ["mexico"],
micronesia: [],
moldova: [],
monaco: [],
mongolia: [],
montenegro: ["montenegro"],
morocco: ["morocco"],
mozambique: [],
myanmar: ["myanmar", "burma"],
namibia: ["namibia"],
nauru: [],
nepal: [],
netherlands: ["the netherlands", "netherlands", "holland"],
newZealand: [],
nicaragua: [],
niger: ["niger"],
nigeria: ["nigeria"],
northKorea: [],
northMacedonia: ["north macedonia", "northmacedonia", "macedonia"],
norway: [],
oman: [],
pakistan: ["pakistan"],
palestine: [],
palau: [],
panama: [],
papuaNewGuinea: [],
paraguay: ["paraguay"],
peru: ["peru"],
philippines: [],
poland: ["poland"],
portugal: [],
qatar: [],
republicCongo: [],
romania: [],
russia: ["russia"],
rwanda: [],
saintKittsAndNevis: [],
saintLucia: [],
saintVincentAndTheGrenadines: [],
samoa: [],
sanMarino: [],
saoTomeAndPrincipe: [],
saudiArabia: [],
senegal: [],
serbia: [],
seychelles: [],
sierraLeone: [],
singapore: [],
slovakia: ["slovakia"],
slovenia: ["slovenia"],
solomonIslands: [],
somalia: [],
southAfrica: [],
southKorea: [],
southSudan: [],
spain: ["spain"],
sriLanka: [],
sudan: [],
suriname: [],
sweden: [],
switzerland: ["switzerland"],
syria: [],
taiwan: [],
tajikistan: ["tajikistan"],
tanzania: [],
thailand: [],
timorLeste: [],
togo: ["togo"],
tonga: [],
trinidadAndTobago: [],
tunisia: ['tunisia'],
turkey: ["turkey"],
turkmenistan: ["turkmenistan"],
tuvalu: [],
uganda: [],
ukraine: ["ukraine"],
unitedArabEmirates: [],
unitedKingdom: [],
unitedStates: [],
uruguay: ["uruguay"],
uzbekistan: ['uzbekistan'],
vanuatu: [],
vatican: [],
venezuela: [],
vietnam: [],
yemen: [],
zambia: ["zambia"],
zimbabwe: [],
}

const CountryData = [
  {
    name: "afghanistan",
    names: countryNames.afghanistan,
    capital: "kabul",
    capitals: ["kabul"],
    abbr: "af",
    borders: [
      countryNames.china,
      countryNames.iran,
      countryNames.pakistan,
      countryNames.tajikistan,
      countryNames.turkmenistan,
      countryNames.uzbekistan,
    ],
  },
  {
    name: "albania",
    names: countryNames.albania,
    capital: "tirana",
    capitals: ["tirana"],
    abbr: "al",
    borders: [countryNames.greece, countryNames.kosovo, countryNames.montenegro, countryNames.northMacedonia],
  },
  {
    name: "algeria",
    names: countryNames.algeria,
    capital: "algiers",
    capitals: ["algiers"],
    abbr: "dz",
    borders: [countryNames.libya, countryNames.mali, countryNames.mauritania, countryNames.morocco, countryNames.niger, countryNames.tunisia],
  },
  {
    name: "andorra",
    names: countryNames.andorra,
    capital: "andorra la vella",
    capitals: ["andorra la vella", "la vella"],
    abbr: "ad",
    borders: [countryNames.france, countryNames.spain],
  },
  {
    name: "angola",
    names: countryNames.angola,
    capital: "luanda",
    capitals: ["luanda"],
    abbr: "ao",
    borders: [countryNames.democraticCongo, countryNames.namibia, countryNames.zambia],
  },
  {
    name: "antigua and barbuda",
    names: countryNames.antiguaBarbuda,
    capital: "saint johns",
    capitals: ["saint johns", "st johns", "st. johns"],
    abbr: "ag",
    borders: [],
  },
  {
    name: "argentina",
    names: countryNames.argentina,
    capital: "buenos aires",
    capitals: ["buenos aires", "buenosaires"],
    abbr: "ar",
    borders: [countryNames.bolivia, countryNames.brazil, countryNames.chile, countryNames.paraguay, countryNames.uruguay],
  },
  {
    name: "armenia",
    names: countryNames.armenia,
    capital: "yerevan",
    capitals: ["yerevan"],
    abbr: "am",
    borders: [countryNames.azerbaijan, countryNames.georgia, countryNames.iran, countryNames.turkey],
  },
  {
    name: "australia",
    names: countryNames.australia,
    capital: "",
    capitals: ["canberra"],
    abbr: "au",
    borders: [],
  },
  {
    name: "austria",
    names: countryNames.austria,
    capital: "",
    capitals: ["vienna"],
    abbr: "at",
    borders: [
      countryNames.czechia,
      countryNames.germany,
      countryNames.hungary,
      countryNames.italy,
      countryNames.liechtenstein,
      countryNames.slovakia,
      countryNames.slovenia,
      countryNames.switzerland,
    ],
  },
  {
    name: "azerbaijan",
    names: countryNames.azerbaijan,
    capital: "baku",
    capitals: ["baku"],
    abbr: "az",
    borders: [countryNames.armenia, countryNames.georgia, countryNames.iran, countryNames.russia, countryNames.turkey],
  },
  {
    name: "the bahamas",
    names: countryNames.bahamas,
    capital: "nassau",
    capitals: ["nassau"],
    abbr: "bs",
    borders: [],
  },
  {
    name: "bahrain",
    names: countryNames.bahrain,
    capital: "manama",
    capitals: ["manama"],
    abbr: "bh",
    borders: [],
  },
  {
    name: "bangladesh",
    names: countryNames.bangladesh,
    capital: "dhaka",
    capitals: ["dhaka"],
    abbr: "bd",
    borders: [countryNames.india, countryNames.myanmar],
  },
  {
    name: "barbados",
    names: countryNames.barbados,
    capital: "bridgetown",
    capitals: ["bridgetown", "bridge town"],
    abbr: "bb",
    borders: [],
  },
  {
    name: "belarus",
    names: countryNames.belarus,
    capital: "minsk",
    capitals: ["minsk"],
    abbr: "by",
    borders: [countryNames.latvia, countryNames.lithuania, countryNames.poland, countryNames.russia, countryNames.ukraine],
  },
  {
    name: "belgium",
    names: countryNames.belgium,
    capital: "brussels",
    capitals: ["brussels"],
    abbr: "be",
    borders: [countryNames.france, countryNames.germany, countryNames.luxembourg, countryNames.netherlands],
  },
  {
    name: "belize",
    names: countryNames.belize,
    capital: "belmopan",
    capitals: ["belmopan"],
    abbr: "bz",
    borders: [countryNames.guatemala, countryNames.mexico],
  },
  {
    name: "benin",
    names: countryNames.benin,
    capital: "porto-novo",
    capitals: ["porto-novo", "porto novo"],
    abbr: "bj",
    borders: [countryNames.burkinaFaso, countryNames.niger, countryNames.nigeria, countryNames.togo],
  },
  {
    name: "bhutan",
    names: countryNames.bhutan,
    capital: "thimphu",
    capitals: ["thimphu"],
    abbr: "bt",
    borders: [countryNames.china, countryNames.india],
  },
  {
    name: "bolivia",
    names: countryNames.bolivia,
    capital: "la paz / sucre",
    capitals: ["la paz", "sucre", "lapaz", "la paz / sucre", "la paz and sucre"],
    abbr: "bo",
    borders: [countryNames.argentina, countryNames.brazil, countryNames.chile, countryNames.paraguay, countryNames.peru],
  },
];

export default CountryData;
